#ifndef BTNARMORYHOVER_H_INCLUDED
#define BTNARMORYHOVER_H_INCLUDED

/* XPM */
static char * btnArmoryHXpm[] = {
"127 63 242 2",
"  	c #3C566E",
". 	c #506C82",
"+ 	c #728A9C",
"@ 	c #92A8BA",
"# 	c #D0E6F4",
"$ 	c #FFFFFF",
"% 	c #F6FFFF",
"& 	c #DCFFFF",
"* 	c #C8FFFF",
"= 	c #B6FFFF",
"- 	c #8AFFFF",
"; 	c #6CFFFF",
"> 	c #56FFFF",
", 	c #4CFAFF",
"' 	c #8EFFFF",
") 	c #C4FFFF",
"! 	c #FEFFFF",
"~ 	c #C4D8E6",
"{ 	c #7AE4FF",
"] 	c #80EAFF",
"^ 	c #7AECFF",
"/ 	c #68E0FF",
"( 	c #5ED8FF",
"_ 	c #50D0FF",
": 	c #48C4FF",
"< 	c #3AC2FF",
"[ 	c #3EC0FC",
"} 	c #28B2FF",
"| 	c #28B0EE",
"1 	c #3CB2F4",
"2 	c #60EEFF",
"3 	c #ACFFFF",
"4 	c #DAFFFF",
"5 	c #6ED0FF",
"6 	c #5CCAFF",
"7 	c #5CC4FC",
"8 	c #56BAF2",
"9 	c #46B6F2",
"0 	c #34AAF0",
"a 	c #28A4E8",
"b 	c #34A8E8",
"c 	c #249CDA",
"d 	c #1C9AE4",
"e 	c #1A94D8",
"f 	c #3CAEEA",
"g 	c #70F6FF",
"h 	c #E4FFFF",
"i 	c #DEF6FF",
"j 	c #4EAEE8",
"k 	c #40AAEA",
"l 	c #4CAAE0",
"m 	c #42B0EC",
"n 	c #2CA0DC",
"o 	c #2C9AD8",
"p 	c #269CE4",
"q 	c #2294D8",
"r 	c #2498D4",
"s 	c #1E90CE",
"t 	c #52EAFF",
"u 	c #56B4E8",
"v 	c #40A4E0",
"w 	c #3AA0DC",
"x 	c #40A8E4",
"y 	c #3AA6E6",
"z 	c #36A6E2",
"A 	c #3AAAE8",
"B 	c #3AA8E4",
"C 	c #32A2E8",
"D 	c #34A2E0",
"E 	c #2A98D4",
"F 	c #168ACA",
"G 	c #2292D0",
"H 	c #B2FFFF",
"I 	c #A0B6C8",
"J 	c #48A2D8",
"K 	c #449AD0",
"L 	c #389CDA",
"M 	c #3AA2E0",
"N 	c #309ED6",
"O 	c #1C8ACA",
"P 	c #1886C6",
"Q 	c #84FFFF",
"R 	c #3898D4",
"S 	c #34A0DA",
"T 	c #228ECE",
"U 	c #46DAFF",
"V 	c #329CDA",
"W 	c #3E98CE",
"X 	c #3894D0",
"Y 	c #3A96D6",
"Z 	c #2A94D2",
"` 	c #76FFFF",
" .	c #1482C2",
"..	c #44EEFF",
"+.	c #1C86C4",
"@.	c #127CBA",
"#.	c #0E7EC0",
"$.	c #1488C4",
"%.	c #1A80BC",
"&.	c #3298D8",
"*.	c #1A84C8",
"=.	c #3492CC",
"-.	c #2890CC",
";.	c #2C96D6",
">.	c #228AC8",
",.	c #3A94C8",
"'.	c #3490C6",
").	c #328CC8",
"!.	c #1A82C0",
"~.	c #0E76B6",
"{.	c #5EF6FF",
"].	c #3298D2",
"^.	c #56F0FF",
"/.	c #2A8CC8",
"(.	c #68FAFF",
"_.	c #308AC2",
":.	c #3294D0",
"<.	c #2288C4",
"[.	c #2084C0",
"}.	c #3298CE",
"|.	c #2288C8",
"1.	c #26A6F6",
"2.	c #2282BA",
"3.	c #60FFFF",
"4.	c #46D4FF",
"5.	c #40C6FF",
"6.	c #58FFFF",
"7.	c #66FFFF",
"8.	c #50E8FF",
"9.	c #48DEFF",
"0.	c #4EFFFF",
"a.	c #52FFFF",
"b.	c #38B6FF",
"c.	c #1A7CB8",
"d.	c #2ACEFF",
"e.	c #38FFFF",
"f.	c #3CFFFF",
"g.	c #42EAFF",
"h.	c #34D6FF",
"i.	c #1678B4",
"j.	c #32C4FF",
"k.	c #34E4FF",
"l.	c #2ED2FF",
"m.	c #38CAFF",
"n.	c #48FFFF",
"o.	c #32ECFF",
"p.	c #28BAFF",
"q.	c #48FAFF",
"r.	c #2AB0F8",
"s.	c #46FFFF",
"t.	c #2ADAFF",
"u.	c #1EB2FF",
"v.	c #2CCAFF",
"w.	c #36F4FF",
"x.	c #44FFFF",
"y.	c #58F4FF",
"z.	c #2A88C2",
"A.	c #2686C0",
"B.	c #2EF4FF",
"C.	c #34FAFF",
"D.	c #2CC0FF",
"E.	c #3EFEFF",
"F.	c #3086C0",
"G.	c #4EEEFF",
"H.	c #5AFFFF",
"I.	c #2CEEFF",
"J.	c #3084BC",
"K.	c #40BEFF",
"L.	c #3A90C4",
"M.	c #1A78B4",
"N.	c #388AC2",
"O.	c #2E80B8",
"P.	c #52F4FF",
"Q.	c #207CB8",
"R.	c #18A4F4",
"S.	c #44E6FF",
"T.	c #2C84B8",
"U.	c #42F2FF",
"V.	c #22BEFF",
"W.	c #2C84BC",
"X.	c #2A86C0",
"Y.	c #2884BC",
"Z.	c #28E8FF",
"`.	c #1474B0",
" +	c #2880BC",
".+	c #1A74B0",
"++	c #146EAE",
"@+	c #168CDA",
"#+	c #34BEFF",
"$+	c #24E6FF",
"%+	c #1270AC",
"&+	c #7AFCFF",
"*+	c #1CC8FF",
"=+	c #2880B8",
"-+	c #2A88BC",
";+	c #1CD8FF",
">+	c #2A7EB4",
",+	c #0E6EAA",
"'+	c #B0CADA",
")+	c #287CB2",
"!+	c #0E82D2",
"~+	c #3C8CC6",
"{+	c #0E6AA8",
"]+	c #1A72AC",
"^+	c #227AB2",
"/+	c #4E9ECE",
"(+	c #5AAADE",
"_+	c #408EC6",
":+	c #54A6D8",
"<+	c #5EB0E2",
"[+	c #0C64A6",
"}+	c #126AA8",
"|+	c #4294CA",
"1+	c #1470A8",
"2+	c #0E68A4",
"3+	c #0C64A2",
"4+	c #0A609E",
"5+	c #247EB6",
"6+	c #4AE4FF",
"7+	c #1268A4",
"8+	c #2884B8",
"9+	c #186CA8",
"0+	c #0A6EB2",
"a+	c #48E2FF",
"b+	c #1066A8",
"c+	c #085C9E",
"d+	c #24D2FF",
"e+	c #2276B0",
"f+	c #307EB6",
"g+	c #287CB8",
"h+	c #1E78AE",
"i+	c #D0FFFF",
"j+	c #2274AA",
"k+	c #065A9A",
"l+	c #3080BC",
"m+	c #206EA6",
"n+	c #1064A2",
"o+	c #1A6CA4",
"p+	c #1E70A6",
"q+	c #3CDCFF",
"r+	c #50B0DA",
"s+	c #64F2FF",
"      . + @ # $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ % % % % $ % $ % % $ % % $ $ % % % % % % % % % % & % & & & & & & & * * * * = = = = = = = = = - - - - - - - ; ; ; ; ; > > , , , > > > > ; ' ) ! . . .       ",
". . . + ~ $ $ = { { { { { { { { { { { { { { { ] ] ] ] ] ] ] ] ] ] ] ] ] ^ { { ^ ^ ^ ^ ^ ^ ^ / ^ / { / ^ ^ ^ ^ { ^ ^ ^ ^ ^ ^ ^ ^ / / / / / / / / / / / / ( / / ( ( ( ( ( ( ( _ _ _ _ _ _ _ _ : < < : : < _ < < < [ [ [ } | | | | | | | | | | 1 [ 2 3 $ .       ",
". + @ # $ 4 5 6 7 8 8 8 7 7 7 7 7 7 7 7 7 7 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 6 7 7 7 6 6 6 6 6 6 6 6 _ 6 _ 6 6 : 7 : 6 : : 6 : : : : : : : : : : : : : : 9 [ 9 9 1 1 1 1 1 0 0 a b a b 0 b a a a a b a c c d c e c c c e c c c a f [ g h       ",
". @ i $ = 6 8 j k l k k j m m j m j m j 9 j 9 j 9 9 9 9 9 9 9 9 8 9 8 9 8 9 9 9 9 9 9 9 9 m 9 9 9 9 9 9 9 9 9 9 9 9 8 9 9 1 f 9 m f 1 m 1 1 1 f 1 m 1 1 f 1 f f f f f 1 1 1 b b b b b b a n n c n n n n c o p p c n e q r e r r r c s s s s s r c a 1 t 4     ",
"+ ~ $ ) 7 u v v v w v v v v x x x x v k x k k k k k k k k m j m m m m m 9 j 9 j m m k k k k k k y z y m m m m m f f A B A f f f A A m f f 1 f 1 f f 1 A b b b A 0 A 0 f f b b C C C C n z A B D B b m f f A b z A z n n n r r E r r s s F F F s s G c z t H   ",
"I ! h 5 u J w K L L w v w v M v M v w v v v v k k k k k k k k k k k k k k k k k m k k y y M y M D B k k k k x B B f B D z B z A A A f A 1 1 1 9 1 9 1 9 1 1 f 0 f A b b b b b n C b b A B A f f m 9 m 9 9 m 1 f m f A D n N D E E G s O P P P O O s G c 0 Q   ",
"~ $ H 8 l J L L R L w w v w v M v w v M v v v x x x k x x x x x k k k k k k k k k x x y y M S M k k k y M M M y A B D D D z B f A A A b 1 f f 1 1 1 9 1 9 9 1 1 m m m f z z b z C b A A A A B B f m m m m m A 9 9 m m m z B B z S n G G O s s s T O s r n U H ",
"# $ 5 u v L K L R R L w L v w v v M v w v M v v v v x x x v x x k k k k k k k k k y y y w D D M k M M D w D M M y D D V D M A f y b b A 1 f A f f f 1 m 9 1 9 f m m 9 9 m f A B A f m f A B z z A f m 9 f m m f 9 9 m f f B f z S n G G G G T G T s s G p | H ",
"i h 5 j J W X Y R R R R L w L w M v w w v M v v v v x x x v v x x x k x x x x x x y y M L w M M M V w D M y k k y y D D D z z b z D C b A A A A A f f 9 m 9 1 m m m m m f f A f f f f f B z z z z A z A f B B f B f f B n N z A D D o s G T T G Z O O O e a ` ",
"i h 5 j w W Y R R R Y R R L L L w w w w w w w w w w v v v v M v v x x x x B v x y M M D L L M L L V w V M k A y A y y y B z V C D D n C D z D b B B f m m m k f f m m k m k z A B B B A D N E Z G G G G Z q E o o E E E E r E S B D N E T G O P P  . .P s a ..",
"i h 7 j w Y R R R Y Y R R Y R R L w w w v w w w w w w w w v v w v M B M z v M B M M D L L S S S S V V S M B z z z y M z D y D n n n n D V n D D D D A A A k A f A A f m f f f A B z z n N o E T O O O O O O s G Z r Z G E G E G o E E O +. . .@.@.@.#. .s d ..",
"i 4 7 j K Y Y X R Y X R R R L L w w w v v v w w w w w v w M M M w w M w M M w M z M S M S M w S N V N S z z S D S L S D D D N E n E o o o o o C N o n D B f A f A A A A A A D D D n o n o E E T G G s s O O O O O O P O +.O $.%. .$. .@.#.@.@.@.@.@.@. .$.e ..",
"# 4 7 l W X X X X X X Y R R Y R L L w w v w w w w w w w M M M w M w M M M M M M w w M M w w S S V S S &.N D S S V V S S V E o N r Z T Z r V o o c o r o o z A n D B D z b D o o o V D n D n Z r E E E n o o G O P *. . . . . .@.#. . .@.#.@.@.@.@.@.@.#.$.e ..",
"# 4 7 l X =.=.X X =.=.=.X R X Y R R R Y L Y R L L L w w w w w w w w M M M L M M M w M w w M w D &.V V V V V V V &.-.o V V V o V ;.O T *.T o D z z z z A A f f k B k A A k B D V V z A z z V V o o E o n D V n E G >.*.*. . . . .@.#.@.@.@.#.@.@.@.@.@.#.F d ..",
"# 4 7 J ,.'.).=.=.=.=.=.=.X X R X R Y Y R Y Y R R R L w L L w L L w M M M M M M M M M M M M D w V V &.&.&.;.;.V Z Z Z o V D o o Z E E o o o D z z B z f f f f k B B A A k B B B z z A A D D z S E ;.o E ;.o E V o ;.T P !. . .@.#.@.~.@.@.@.@.@.@.@.@. .s p ..",
"# h 7 J W '.).=.=.=.=.=.=.X X Y R Y Y Y R Y L R Y R L L L L L L L L w w w w w w y M M w w L L V V &.;.&.&.;.Z ;.Z -.Z T T o V ;.;.o G E ;.E V z z z B A A f k m k y y A z A k k k k k m A B B D V D N V G O *.+.O G ;.E Z G +.$. .@.@.@.@.@.@.@.@.@.#. .s a {.",
"# h 7 J Y '.).).=.=.=.=.=.=.=.X Y Y R Y Y Y R R L L L L L L R R L L w w L w L L L L L L L L L L &.].].Z ;.Z ;.;.&.&.V D V V V V ;.Z Z o V V o M D o D D z f f f A y z f f A k B z z A A A B V o V S V V S L G T O O O T Z G r T +. .@.@.@.@.~.@.@.@.@.P s a ^.",
"# 4 8 l X '.).).).).=.=.X X X X X X R R Y R R R R R L L L L L R R R L L w L L R L L L L L L L &.&.&.].].;.-.o N V &.Z V ;.].V S Z T Z Z E ;.V z k D D D V z A A B B z z A k A A B z y y B y D D V V S V &.S V o n V o T O O T -.G  .@.@.@.~.~.~.@.@.!.P G a ` ",
"# 4 8 J X '.).).).).).=.X =.=.X =.X R X R R R R R R Y L L L L L R R R L L L L L L L L L L &.&.&.Z ].Z ;.-./.T V &.].;.].;.;.-.].L T Z T Z V N S D D V o &.S D V D z V D B y B B M z D M B B D D V S V S V E -.G o o E Z T O +.O >.+.+.%.@.@.~.@.%.%.@.+.r a (.",
"# 4 8 J ,.)._.).).).'.).=.=.=.=.=.=.=.:.X X X X X R R R R R R L R R ].L L R R R L R ].].R &.].].].].-.:.>./.T N -.Z ].Z -.-.].].Z -.+.!.-.-.&.&.E Z Z ;.-.Z &.V S D N D D B B B z D N M M D B S N D D N V S N E Z T Z T G ;.T P O %.!.%.%.+.<.[.@.@.%.+.r b ` ",
"~ 4 8 J ,._._._._._.).'.'.'.'.'.=.=.=.=.}.X }.].X R X }.R R R R }.R R ].}.}.].].].].].].].].].}.}.-.Z /./.<.<.-.].-.].<./.>.:.].].:.!.%.>.Z Z Z V &.T -.>.|.>.-.Z N N N ;.E N S D S S S N S z z S N S N N D S E E -.s E N -.+.+. .@.@.@.!.+.<.+.%.%.!.O G b ` ",
"~ 4 8 J ,._._._.).'.'.).).).).).:.=.:.}.}.X }.}.}.}.}.}.:.].].].}.}.}.}.}.}.}.}.:.].R ].:.].].].:.-./.-.<.<.<.>.[./.T [.!.[.-.>.:.Z >.[.!.>.>.Z Z ;.;.-.+.!.+.T -.T -.>.Z /.T ;.Z ;.].].N D S S N }.E -.-.E E -.Z >.>.>.>.+.%.P %.%.P +.-.+.+.+.%.%.+.T E b ' ",
"~ 4 8 J ,.)._.).).).).).).).).).L L :.:.:.:.}.:.:.}.}.}.}.}.].].}.}.}.:.:.:.}.:.:.].].:.Z :.-.:.:.-.-./.-./.>.|.[.>.!.%.!.!.[.-.].;.-.-.[.%.!.!.>.-.>.-.1.1.1.a |.+.!.+.>./.>.-./.-.;.Z Z &.L L &.].-.-.}.Z Z E -.-.Z T >.!.@.!.!.%.>.-.>.>.[.[.%.2.[.>.N 1 ` ",
"# 4 8 J =._._._.).).).).).).).1 3.4.'.:.=.:.:.:.=.=.5.6.7.7.7.6.6.6.7.6.8.b :.:.}.Z -.C 9.0.6.a.b./.-./.<.<.>.-.<.[.[.!.c.d.e.f.g.h.).>.[.i.%.%.G j.g.k.l.m.m.k.n.o.p.<.+.-.Z -.<.T h.n.a.6.a.> q.a.0.g.5.;./.>.r.g.s.n.s.t.u.@.%.%.[.q v.w.x.w.v.G !.<.N f ' ",
"# 4 8 J =._._._._.).).).)._.).6.3.> '.).).).=.'.).'.=.X y.7.6.}.=.'.N 9.6.6.5.-./.-.-.-.-.V a.a.9./.<.<.z.A.<.[.<.[.[.c.O B.C.D.%.[.[.[.+.%.2.D.e.v.T [.[.[.+.+.O d.f.f.1.<.|.+.!.%.+.p a.a.b.-.Z Z b.E.a.n.;.-.>.<.r.s.f.D.i.@.@.<.[.<.[.w.v.2.!.!.[.<.n m ' ",
"# 4 8 K '.F.F.F._._.).)._.).1 > 3.3.1 ).'.'.'.'.).'.=.=.9.7.6.=.=.-.=.:.G.H.> ;.-././.>.-.-.n.> 0.>.z.A.2.z.[.[.[.[.2.!.d.e.e.u.c.c.i.%.>.[.d.e.} [.[.<.[.[.>.+.%.%.} f.n.p.<.!.%.@.!.<.a.s.1.-./.Z -.c a.a.v.-.|.>.>.} n.I. .@.!.<.>.>.v.o.>.!.!.+.[.>.E 0 ' ",
"# 4 8 K '.J.J.J.F._._._._._.9.K.9.3.8.).'.'.)._.).).).L.9.H.6.'.-.)./.).b.H.a.1 =.-././.-.>.> h.n.h.2.2.A.2.A.A.[.2.[.a w.v.e.D.%.%.M.c.%.D.B.l.c.%.[.<.[.[.>.>.%.%.%.v.f.x.q [.!.+.c.!.e.C.r.[.-.-.>.|.q.f.q.-.-.>./.T k.C.d.!.[.+.<.p x.q !.!.!.!.<.>.E b ` ",
"# 4 u K N.J.O.O.F.F.J._.F.L 6._.L 3.3.w ).).)._.).).).).4.H.P.).)././.-.b.a.a.o /./././.-./.n./.n.x.a A.2.2.Q.2.%.2.2.k.r.D.e.j.!.%.2.%.G C.B.p %.%.+.<.>.<.>.<.2.@.%.O C.C.k.[.>.*.!.c.C.B.d *./././.<.k.s.h.>.:.>.[.[.c w.s.R.%.[.%.k.} !.%.%.%.%.!.<.E f ' ",
"# 4 u K _.J.J.J.F.J.J.J.F.9.5._.N.P.3.4.).).)._.)._._._.4.3.P._././././.S.a.K./././././.).r.g.A.m.x.q.-.A.[.2.2.[.Q.} k.%.D.x.D.!.2.c.%.} I.I.c.c.c.%.[.[.<.<./.[.<.c.c.t.B.e.<.>.|.|.%.B.B.d c.%.!.<.q e.k.+.%.<.+.%.[.c.m.s.E.>.%.D.v.%.%.%.%.%.%.%.<.N f ' ",
"~ 4 u W _.J.T.J.F.J.J.J.&.> )._._.b.3.> X _.).).)._._._.4.3.P.z.z./.V 9.q.0 z././././.z.z.0 a./.A.q.x.j.2.2.2.2.c.T U.T Q.D.n.D.[.%.2.c.l.w.C.c.%.c.c.c.c.!./.%./.<.[.c.V.e.e.R.%.+.[.!.C.C.p %.%.c.1.k.v. .M.c.i.c.c.@.!./.U.n.v.d k.*.c.%.[.%.%.%.%.[.Z b ` ",
"~ 4 u K _.T.T.J.J.F.F.W.5.4.F.X._._.> 3.K._.).).).)._./.4.3.> G.G.> a.n.-./.X.z.z./.z.z.<.1 U.A.Y.a 0.x.p A.2.Q.Q.k.p.c.Q.j.x.j.%.c.c.2.t.e.w.c.M.M.M.M.c.%.c.2./.<.<.%.p.C.C.1.c.%.c.c.C.C.t.t.t.I.Z.u.i.i.i.@.i.`.~.i.c.%.p s.x.I.d %.%.%.!.%.!.c.%.>.E B ` ",
"# 4 u W _.T.W.J.W.F.X.).6.8.8.8.P.P.6.3.> '.)._._._.)._.4.> G.X.X.C n.> S. +Y.z.z.z.z.A.z.0 g.2. +[.S.x.S.2.[.2.1.g.2.%.2.D.e.D.c.%.%.M.D.w.w.d .+c.M.%.c.%.Q.%.M.%.[.[.p.C.C.*.i.c.c.c.B.I.d ~.++V.Z.I.@+M.i.i.i.~.`.@.c.c.c.d.C.k.c.c.%.%.%.%.c.c.!.+.-.n (.",
"# 4 u K _.O.O.J.W.W.W.5.9.J.F.F._.F.=.> 3.1 _._.F.F.z._.4.> G.X.X.z.0 0.a.#+Y.X.X.Y.X.z.<.b.S.A.A.A.o x.n.p.2.|.w.p 2.Q.2.#+C.p.Q.c.M.M.1.C.w.D.c.Q.2.2.Q.2.2.M.c.M.c.c.h.I.d.c.c.c.c.c.$+$+@+%+i.c.d.$+k.@.`.`.`.`.`.i.c.c.c.u.w.t.c.c.%.M.i.M.M.M.%.!.T c &+",
"~ 4 u K _.J.O.T.Y.Y./.> :.J.F.F._.F.F.9.> 8.F._.F.X.z.F.4.> S.X.X.X.X.#+0.> 0 X.X.X.z.z.z.m.S.<.X.X.A.j.E.U.T h.#+Y.2.2.2.j.E.t.Q.Q.Q.2.2.t.E.o.*.Q.c.c.Q.c.M.M.M.M.c.!.w.B.p c.c.i.i.`.$+$+@+i.i.`.@.t.$+*+`.`.`.`.`.M.i.M.M.u.o.d.c.M.M.M.i.M.M.M.M.c.+.o (.",
"~ 4 u K '.T.T.T.Y.=+4.8.J.J.F.F.F._.F.L > > :.F.F.X.X.J.m.> 8.Y.-+z.X.A.9.> > C z.z.z.z.X.5.g.A.Y.Y.A./.U.E.k.U./.Y.2.2.2.#+C.h.Q.2.Q.%. +T w.E.h.Q.%.Q.c.M.c.Q.c.c.c.l.C.1.M.i.i.`.`.`.$+$+e `.%+%+`.F ;+$+u.`.`.`.`.M.M.`.M.u.Z.d.i.i.i.M.M.M.`.`.i.c.+.r {.",
"~ 4 u W _.T.>+=+=+:.> b.O.O.F.F._.F.F.F.G.> 4.W.-+-+-+W.5.> S.X.-+z.-+Y.z.S.> > 0 z.X.X.X.g.g.X.Y.Y.X.2.} E.x.0 2.2.2.2.2.j.E.9.%.Q.%.2.2.%.[.h.E.l.T M.M.c.M.c.c.+.v.o.1.i.i.i.`.`.%+%+$+$+e ,+,+%+,+,+@+;+$+u.@.`.`.`.i.`.`.u.$+d.`.M.M.i.`.%+`.`.`.c.!.G ..",
"'+4 u W F.>+)+&.0 S.> 5.C Y.W.W.X.X.&.y G.> > 4.b =.0 b.> > > 5.0 Y.Y.Y.X./.4.> > m.-.0 j.a.n.#+0 A.Y.2.A.S.S.A.2.2.2.E 1.g.E.E.r.p Q.2.2.c.c.%.1.l.k.v.1.p p p v.k.D.%.M.`.`.`.`. .@+V.;+;+*+@+~.,+%+%+`.F ;+$+*+@+`.`.`.@+R.;+$+$+u.e *.`.%+`.%+`.i.c.+.G ..",
"'+4 u W F.>+>+&.D V C C D Y.W.W.W.W.).0 0 y 0 0 0 =.D b b 0 0 0 C Y.Y.X.z.z.z.V K.m.5.b.b 0 0 0 0 A.A.A.A.D n A.Y.2.2.Z C a a a a a Q.Q.2.c.M.Q.M.M.+.p p.p.p.r.e M.M.M.i.`.`.`.`.@.!+!+!+!+!+!+~.%+%+`.`.%+%+@+R.R.R.++`.e @+@+@+@+@+e  .`.`.`.`.`.`.c.>.r ^.",
"I 4 u W J.>+)+J.J.F.F.F.N.>+>+=+Y.Y.F.L.~+'.L.L.,.F.'.'.'.,.,.,.'.-+-+F.z.z.z.=.W K K ,.=.=.'.'.'.Y.X.2.Y.).).A.A.Y.A.z.)._._._._.z.M.M.c.M.M.c.Q.Q.2.z.,.=.'._.2.M.M.`.`.`.%+,+,+{+]+]+M..+]+M..+%+%+%+,+,+,+M. +X. +`.`.Q.Q.Q.Q.^+Q.Q.M.%+%+`.`.`.`.i.%.r (.",
"I h j ,.J.)+)+O.N./+(+_+J.)+>+>+=+>+F.N.:+<+<+J ,._.'.W (+<+<+K '.W.z.z.X.X.J <+<+K X.'.K <+(+X '.2.2.X.X.:+J -+A.Y.Y._.'.J (+:+=.-+^+c.c.M.c.2.=.J J ,.X.X.Y.Y.'.K '.M.%+%+%+{+[+}+]+J.|+|+L.^+.+%+,+,+[+]+L.|+L.^+,+1+%+Q.Y.K K /+X.^+.+%+1+`.1+M.`.c.!.r ^.",
"I 4 j ,.J.>+>+>+)+J.(+_+>+>+=+=+=+=+=+=+:+(+J -+X.-+-+T.W <+:+X.z.z.X.z.F.J <+<+'.z.z.X.z.J :+Y.Y.X.X.X.W <+<+,.A.A.2.2.2.,.:+/+Q.c.^+M.c.2.Y.K :+,.M.%+M.M.M.M.`..+F.|+=+{+{+2+3+4+3+3+|+|+.+{+,+2+{+{+.+|+W J.%+,+1+1+%+%+%+F.K |+++%+%+%+%+,+%+%+M.`. .G t ",
"@ h j |+J.>+>+>+>+>+|+/+O.)+)+>+=+>+=+F.<+<+_.Y.Y.T.W.W.K <+:+X.X.X.X.z.J <+(+'.X.Y.Y.X.z.K J X.-+z.X._.(+<+:+l Y.2.2.2.5+,.:+K Q.c.c.^+c.Y.J /+,.%+1+1+M.M..+`.%+%+1+_.|+^+2+3+3+3+3+3+|+|+.+3+3+2+[+++,.|+J.{+,+{+%+%+++%+%+W.K ~+%+++++++++++++,+{+%+!.s ^.",
"@ 4 u ,.J.>+)+>+>+>+O.:+J.)+)+>+=+>+=+/+<+J Y.Y.Y.Y.T.Y.K <+:+X.X.X.z.W (+(+'.X.X.X.Y.X.z.K J X.z.z.X.K (+(+_.K W 2.Q.Q.2.,.:+K Q.M.Q.Q.c.K /+K ]+%+1+`.M..+`.%+++}+2+%+|+|+.+3+3+2+3+3+|+|+]+3+3+3+2+~+|+N.{+{+,+,+,+++++++,+J.K ~+++++++++,+.+%+`.2+,+~.F 6+",
"@ 4 l L.O.)+)+>+>+>+)+_+K >+>+)+=+=+J.(+<+'.Y.Y.T.T.-+-+K (+/+Y.X.F.'.:+:+,.-+Y.Y.-+-+X.z.,.J -+z.-+z.:+(+=.2.Y.:+X.Q.Q.2.,.:+'..+M.M.M.W./+/+F.++1+1+M.]+1+}+2+2+2+{+}+_.|+F.3+3+2+3+3+|+|+++[+2+3+N.|+~+,+,+{+,+,+,+1+%+}+}+O.|+~+}+7+{+}+}+}+}+}+3+{+~.O 6+",
"@ 4 l L.O.)+)+>+>+)+^+)+:+/+/+/+/+/+:+(+:+Y.=+=+8+T.W.T.|+(+/+Y.X.)./+K |+X.X.-+-+-+-+-+X.'.W z.X.8+W J K 2.5+5+_.J Q.Q.Q.N.:+_..+.+.+.+)./+K ^+}+%+`.`.}+2+2+[+2+2+{+}+Y.|+|+2+3+3+2+3+|+|+]+3+3+W._+|+9+{+{+2+{+{+{+}+}+}+7+J.|+~+2+2+2+2+3+2+2+4+4+2+0+$.a+",
"@ 4 :+L.O.)+)+>+)+)+)+)+_+|+>+>+)+=+(+(+L.Y.Y.=+=+W.Y.=+,.:+:+K W K W ,.z.X.Y.z.z.X.X.X.Y._.'.Y.=+W.|+K Y.Q.^+Q.Q.K ,.M..+_./+_.]+]+]+]+,./+K 7+2+1+{+%+}+{+2+3+2+2+2+2+)+|+_+]+3+3+3+3+|+|+N.F.N.|+|+^+2+2+7+2+b+b+2+b+}+}+]+|+K _+.+}+2+3+3+3+3+c+4+3+0+ .d+",
"@ 4 l ,.O.)+)+)+e+e+e+e+f+:+T.>+e+N.(+:+O.=+ +Y.W.=+=+5+_+:+|+W.X.X.F.'.'.F.X.X.X.Y.Y.Y.Y.W.'.=+=+-+L.F.Q.Q.Q.^+^+g+K ^+]+_./+F.]+]+1+}+N.K |+3+3+3+2+,+}+}+2+3+{+2+2+2+g+_+|+]+3+2+3+3+_+_+9+3+3+2+h+L.T.1+{+2+2+2+2+}+}+b+N.|+J..+N.b+4+3+3+4+c+c+4+3+0+#.d+",
"I i+l ,.O.)+)+)+j+e+e+)+)+|+~+)+)+/+:+_+=+=+Y. +W. +>+=+|+/+,.W.W.W.Y.Y._.'.X.Y.X.Y.Y.=+=+Y.F.5+T._.J.5+Q.Q.Q.M..+.+F.|+]+F.K F.]+]+}+2+e+|+|+3+3+3+3+2+{+2+2+2+7+2+3+3+J._+_+3+2+[+3+3+_+_+]+[+3+2+2+}+|+N.1+2+2+b+7+7+2+g+|+~+}+3+^+f+c+c+c+c+c+k+4+3+0+#.d+",
"I i+l L.f+)+)+j+j+e+e+e+^+f+/+g+l+/+:+W.=+>+=+ +=+=+5+=+L.|+N.Y.Y.Y.Y.Y.J.N.).Y.Y.=+5+5+5+5+-+^+F._.Y.Q.Q.M..+M..+.+]+L.g+W.|+W.]+7+3+3+7+N.N..+b+{+3+2+3+3+}+7+7+}+2+}+~+~+f+3+3+3+3+[+_+~+]+b+[+b+{+[+J.~+g+b+2+2+2+2+}+N.~+9+3+4+4+l+9+c+c+c+c+c+c+[+0+#.d+",
"I i+l L.f+)+e+j+j+]+e+e+e+)+N.F.N.K ~+)+^+)+)+)+g+g+>+=+F.N.F.=+=+T.W.=+X._._.Y.5+5+5+5+^+Q.=+=+Y.Y.^+M.M..+]+.+.+.+]+.+J.g+J.h+b+3+3+3+3+]+l+^+}+b+b+b+b+7+7+b+}+}+7+e+l+J.7+3+3+3+3+3+l+J.9+3+{+3+[+3+^+l+g+3+2+b+2+3+g+l+e+3+4+4+c+4+)+4+c+c+c+c+c+3+0+#.d+",
"I = l L.O.)+m+m+9+m+j+j+e+)+O.J.N.N.O.)+e+e+)+e+)+)+=+>+T.J.W.Y.T.-+W.T.W.F.W.=+5+5+5+^+^+^+=+5+5+h+h+h+h+.+h+h+.+]+]+]+]+j+]+]+}+n+3+3+3+3+]+e+9+[+7+b+b+7+7+}+}+7+++^+^+9+3+3+3+3+3+3+e+e+}+2+b+3+3+3+e+e+9+3+3+3+3+b+e+]+4+c+c+c+k+k+n+o+c+k+k+k+c+4+0+#.d+",
"I i+J '.>+j+m+m+m+p+p+j+e+e+j+f+f+l+e+^+)+^+)+)+^+)+^+^+T.W.T.=+=+8+Y.Y.W.W.=+5+^+^+^+^+^+^+h+h+.+]+h+]+.+.+]+]+]+1+9+7+7+9+9+]+7+3+3+3+3+3+3+9+]+p+}+2+7+7+}+}+}+]+e+h+1+.+.+]+}+7+2+n+p+]+7+4+3+3+n+o+p+9+3+3+3+3+}+p+9+n+c+c+c+k+k+k+k+n+n+k+k+k+k+4+{+#.d+",
"I H J _.)+m+m+m+p+j+j+e+j+j+j+j+f+)+j+j+e+^+)+e+j+e+)+>+O.O.T.T.=+T.W.T.=+5+Q.5+^+j+h+]+1+]+]+j+]+]+]+.+h+.+.+.+]+n+9+9+}+]+]+1+1+9+n+n+3+3+3+3+1+9+h+]+]+]+]+e+e+]+]+.+^+Q.^+h+9+}+]+]+p+]+]+p+]+]+9+9+n+4+3+3+n+9+9+9+o+n+4+c+k+c+c+4+n+7+7+n+n+c+k+4+{+#.d+",
"I H J N.j+m+m+m+p+j+j+e+e+j+e+j+j+j+j+j+e+j+j+j+j+e+e+)+=+=+g+)+)+5+5+^+^+e+e+e+.+9+7+7+7+1+9+h+h+h+h+h+h+h+]+}+9+]+]+]+1+1+9+}+}+}+}+n+n+n+n+n+}+}+}+}+]+]+]+1+++]+.+]+}+}+7+7+7+n+b+b+3+3+3+3+3+3+4+4+4+4+3+3+3+4+4+c+k+c+c+c+k+c+c+c+c+k+k+k+c+c+k+4+0+#.d+",
"'+i+J J.j+m+m+p+p+j+j+e+j+j+j+j+p+p+j+m+]+j+j+j+e+e+e+g+g+)+)+)+)+e+e+^+e+e+]+9+n+n+7+9+7+9+h+h+h+h+h+e+]+9+]+9+]+9+]+]+1+9+}+7+}+1+}+7+7+2+3+7+}+}+.+]+++++++++]+++7+}+1+}+7+}+7+n+b+n+b+n+n+3+3+3+3+3+3+3+4+3+4+c+4+k+k+c+c+c+k+k+k+k+k+k+k+k+c+k+c+4+0+#.q+",
"I h J _.j+m+m+m+p+m+j+j+j+j+j+j+m+p+p+p+j+j+j+p+j+e+)+)+)+)+)+^+e+e+j+e+e+p+n+n+n+n+7+9+9+h+e+M.h+h+.+9+]+1+9+9+9+1+]+]+1+9+1+}+}+}+}+}+}+n+b+7+}+++9+++++++++++++b+b+}+++}+b+}+b+n+n+3+7+}+}+b+3+3+3+3+2+3+4+4+c+c+c+c+c+c+k+c+k+k+k+k+k+k+k+k+k+k+c+3+0+#._ ",
"@ ! 5 '.)+j+p+m+m+m+m+m+m+j+m+m+o+o+o+j+j+j+p+m+p+e+^+)+^+^+e+^+)+^+e+j+o+n+7+n+7+}+}+9+h+^+M.M.M..+++9+++9+++9+]+]+]+9+9+1+}+9+9+9+}+7+}+}+b+++++1+1+++}+}+7+}+}+}+}+}+++b+b+}+}+b+b+}+}+++}+[+[+[+4+3+3+3+3+4+4+4+4+4+c+c+k+k+k+k+k+k+k+k+k+k+k+k+c+[+0+d /+",
"+ ~ H W J.e+j+p+m+m+m+m+p+p+p+m+o+m+j+j+j+m+]+m+p+e+)+)+)+e+)+)+g+e+9+7+7+9+n+7+7+7+9+h+Q..+h+.+++]+]+++9+9+}+]+]+]+9+9+9+9+7+}+}+7+}+}+}+}+++++++++++++}+}+}+}+}+b+}+}+b+}+}+b+b+}+}+}+}+}+}+b+3+[+3+3+3+3+3+4+4+c+4+c+c+k+k+k+k+k+k+k+k+k+k+k+k+k+c+{+~.<   ",
"  + i+5 ,.J.e+j+m+m+m+j+j+j+j+p+m+j+j+j+j+j+p+m+j+)+)+)+)+)+g+g+e+9+o+7+o+7+n+7+9+9+h+h+^+^+^+]+1+]+]+.+++++]+.+]+]+]+]+9+}+}+}+++}+}+}+}+}+++++.+]+.+]+]+++9+9+}+b+}+b+b+}+}+b+b+}+++}+}+}+b+[+b+b+3+3+3+3+3+3+3+3+3+3+4+4+4+c+4+4+4+4+4+4+4+c+4+4+{+0+a /+  ",
"  . '+i+5 L.T.)+)+j+)+>+)+)+)+^+j+h+)+)+)+j+j+^+T.T.J.J.W.=+5+5+^+]+]+o+7+o+o+o+p+h+5+5+^+=+5+.+.+.+.+.+]+M.M.M.e+M.^+M.]+++]+1+1+++,+1+%+%+1+M.M..+M.M..+.+.+++%+%+1+}+}+%+1+%+%+%+%+`.`.`.}+}+}+}+7+2+2+2+{+}+}+2+2+2+2+{+2+3+3+2+2+2+2+7+n+3+3+{+0+d 8     ",
"    + '+i+5 W L._.N._.N._._.T.-+T.T.T.T.T.=+=+'.L.,.,.,.'.-+W.-+-+-+Q.^+h+h+h+h+Q.-+_.)._././.2.%.c.c.c.%.A.[.[.A.[.z.A.Q.%.2.M.M.i.i.c.c.c.M.%.[.[.[.2.Q.%.%.%.c.c.i.i.i.i.c.i.c.c.c.%.%.i.`.`.`.`.`.`.i.i.c.i.M.M.i.i.i.i.i.`.%+`.`.`.`.%+,+,+0+~.| r+      ",
"      + '+$ H 5 :+J J J J w K v w K L J L Y l l l l l J l l v w w J -.-.-.-.-.Z }.w v v v v V -.-.T -.G :.;.;.;.;.;.&.;.-.-.T >.>.O O T T T T T G G Z G T T T T T O O O +.O O *.T O O G O *.*.*.*.!.*.P +.O T G O O >.*.O *.*. . .P P *.*. . . .R._ .         ",
"      . + @ # $ h i+H H H H H H = ) = = = 4 4 h h h ) ) h h 4 4 = = Q Q &+Q Q Q = = = = = = &+g g s+s+&+&+&+Q Q Q &+g &+&+2 2 s+s+2 s+^.^.t 2 s+t s+s+s+2 ^.^.t 6+6+6+6+6+6+6+t 6+t t {.t t 6+a+a+q+6+6+6+6+6+6+t t 6+6+6+6+a+6+6+a+a+a+q+q+a+_ /+            "};

#endif // BTNARMORYHOVER_H_INCLUDED
