#ifndef BTNFORUMHOVER_H_INCLUDED
#define BTNFORUMHOVER_H_INCLUDED

/* XPM */
static char * btnForumHXpm[] = {
"128 63 244 2",
"  	c #365266",
". 	c #2A4458",
"+ 	c #6E8692",
"@ 	c #A0B6C2",
"# 	c #D0E0EA",
"$ 	c #FFFFFF",
"% 	c #F6FFFF",
"& 	c #DEFFFF",
"* 	c #C8FFFF",
"= 	c #B6FFFF",
"- 	c #88FFFF",
"; 	c #6CFFFF",
"> 	c #56FFFF",
", 	c #4AFCFF",
"' 	c #90FFFF",
") 	c #C0FFFF",
"! 	c #E6FFFF",
"~ 	c #223C4E",
"{ 	c #466274",
"] 	c #567284",
"^ 	c #BCCED8",
"/ 	c #78E4FF",
"( 	c #80EAFF",
"_ 	c #78ECFF",
": 	c #6AE2FF",
"< 	c #5EDAFF",
"[ 	c #50D0FF",
"} 	c #48C4FF",
"| 	c #3EC0FE",
"1 	c #36B8FF",
"2 	c #26AEEE",
"3 	c #2AB2F0",
"4 	c #60EEFF",
"5 	c #A8FFFF",
"6 	c #8EA2AE",
"7 	c #D8FFFF",
"8 	c #7AD6FF",
"9 	c #5AC4FE",
"0 	c #56BAF2",
"a 	c #5CCAFF",
"b 	c #46B6F2",
"c 	c #3CB2F4",
"d 	c #32A8EA",
"e 	c #28A4E6",
"f 	c #36AAF2",
"g 	c #249CDC",
"h 	c #1A94D8",
"i 	c #2498D4",
"j 	c #3AACE8",
"k 	c #78FCFF",
"l 	c #D0FAFF",
"m 	c #B4FFFF",
"n 	c #50AEE6",
"o 	c #40AAEA",
"p 	c #4CAADE",
"q 	c #40A8E6",
"r 	c #42B0EC",
"s 	c #54B4EA",
"t 	c #3CAEEA",
"u 	c #32A4E6",
"v 	c #269EE4",
"w 	c #2E9CDA",
"x 	c #2EA0DC",
"y 	c #2094D8",
"z 	c #1E90CE",
"A 	c #52EAFF",
"B 	c #40A2E0",
"C 	c #3AA0DE",
"D 	c #3AA8E4",
"E 	c #36A6E2",
"F 	c #34A2E0",
"G 	c #2A98D4",
"H 	c #1888C8",
"I 	c #B8F0FF",
"J 	c #F4FFFF",
"K 	c #6CCCFF",
"L 	c #3A9CDA",
"M 	c #3AA2E0",
"N 	c #3AA6E8",
"O 	c #34A0DC",
"P 	c #2492D0",
"Q 	c #1A86C8",
"R 	c #1686C6",
"S 	c #1C8ACA",
"T 	c #78FFFF",
"U 	c #A6FFFF",
"V 	c #4AA2D6",
"W 	c #389AD4",
"X 	c #228ECE",
"Y 	c #3EDAFF",
"Z 	c #309ED6",
"` 	c #3896D0",
" .	c #1AA6F0",
"..	c #4098CE",
"+.	c #3896D6",
"@.	c #329CDA",
"#.	c #1684C4",
"$.	c #1482C0",
"%.	c #44EEFF",
"&.	c #3098D6",
"*.	c #1C86C4",
"=.	c #107EC0",
"-.	c #127CBA",
";.	c #1C98E6",
">.	c #0E78B8",
",.	c #3494CE",
"'.	c #2C96D4",
").	c #3A90C6",
"!.	c #3490CC",
"~.	c #328CC6",
"{.	c #2A94D0",
"].	c #1C82C0",
"^.	c #2A90CC",
"/.	c #5EF6FF",
"(.	c #3298D2",
"_.	c #288CC8",
":.	c #228AC8",
"<.	c #1A80BC",
"[.	c #6AFCFF",
"}.	c #308AC2",
"|.	c #2084C2",
"1.	c #2288C4",
"2.	c #3290C6",
"3.	c #3298CE",
"4.	c #3CBCFF",
"5.	c #1A7CB8",
"6.	c #2082BA",
"7.	c #48D2FF",
"8.	c #58FFFF",
"9.	c #62FFFF",
"0.	c #5CFFFF",
"a.	c #54FEFF",
"b.	c #50EEFF",
"c.	c #4AE2FF",
"d.	c #54FFFF",
"e.	c #32CAFF",
"f.	c #46FCFF",
"g.	c #46FFFF",
"h.	c #4EFFFF",
"i.	c #3EFFFF",
"j.	c #34E4FF",
"k.	c #30ECFF",
"l.	c #2EF0FF",
"m.	c #2ED8FF",
"n.	c #2ABAFF",
"o.	c #26AAFF",
"p.	c #28C2FF",
"q.	c #36FAFF",
"r.	c #38D0FF",
"s.	c #2CB0FF",
"t.	c #30D2FF",
"u.	c #3CFFFF",
"v.	c #48FFFF",
"w.	c #52FFFF",
"x.	c #4CFFFF",
"y.	c #60FFFF",
"z.	c #5EFFFF",
"A.	c #3AE2FF",
"B.	c #2A88C2",
"C.	c #168EDA",
"D.	c #26A8F8",
"E.	c #38DAFF",
"F.	c #469AD0",
"G.	c #2E86BC",
"H.	c #3086C0",
"I.	c #2686BE",
"J.	c #30F4FF",
"K.	c #1676B4",
"L.	c #368CC2",
"M.	c #3084BA",
"N.	c #2684BE",
"O.	c #207CB8",
"P.	c #3EEEFF",
"Q.	c #38F4FF",
"R.	c #2E80B8",
"S.	c #18B0FF",
"T.	c #1A78B4",
"U.	c #2C84B8",
"V.	c #2A86C0",
"W.	c #22C8FF",
"X.	c #1474B8",
"Y.	c #1474B0",
"Z.	c #2A82BA",
"`.	c #24E6FF",
" +	c #1270AC",
".+	c #22DEFF",
"++	c #1A74AE",
"@+	c #2A88BC",
"#+	c #3EC8FF",
"$+	c #2880B8",
"%+	c #22E4FF",
"&+	c #1CCEFF",
"*+	c #2A7EB4",
"=+	c #2A80BA",
"-+	c #106EAA",
";+	c #287CB2",
">+	c #0E82D2",
",+	c #0C68A4",
"'+	c #0E6AA6",
")+	c #2882B8",
"!+	c #146EAE",
"~+	c #56EEFF",
"{+	c #1872AC",
"]+	c #126CA8",
"^+	c #3C92C8",
"/+	c #2478B0",
"(+	c #4292CA",
"_+	c #5CACDE",
":+	c #54A6DA",
"<+	c #5EB0E2",
"[+	c #1E78AE",
"}+	c #0C62A2",
"|+	c #146EA8",
"1+	c #247EB4",
"2+	c #0C64A6",
"3+	c #287CB6",
"4+	c #48E2FF",
"5+	c #3C8CC6",
"6+	c #4AE4FF",
"7+	c #1068A8",
"8+	c #1064A2",
"9+	c #0A5E9E",
"0+	c #0A6EB2",
"a+	c #1E70A8",
"b+	c #26CEFF",
"c+	c #2276B0",
"d+	c #2272AC",
"e+	c #1268A4",
"f+	c #166CA8",
"g+	c #085C9C",
"h+	c #C4FFFF",
"i+	c #206EA6",
"j+	c #1C6EA4",
"k+	c #065A98",
"l+	c #307EB4",
"m+	c #4690BC",
"n+	c #AAFCFF",
"o+	c #1A3440",
"p+	c #FCFFFF",
"q+	c #C6FFFF",
"r+	c #82FFFF",
"s+	c #70F6FF",
"t+	c #66F2FF",
"u+	c #5EA0C0",
"    . . + @ # $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ % % % % $ % $ % % $ % % $ $ % % % % % % % % % % & % & & & & & & & * * * * = = = = = = = = = - - - - - - - ; ; ; ; ; > , , , , > > > > ; ' ) ! .       . ~ ~ ",
"  { ] + ^ $ $ ) / / / / / / / / / / / ( / ( / ( ( ( ( ( ( ( ( ( ( ( ( ( _ / / _ _ ( _ ( _ _ : _ : : / / _ _ _ / _ _ _ _ _ _ _ _ : : : : : : : : : : : : < < : < < < < < < < [ [ [ [ [ [ [ [ } | | } } } [ | | | | | | 1 2 2 2 2 2 3 3 2 2 3 1 | 4 5 $ {     . ~ ",
"  ] 6 ^ $ 7 8 9 9 9 0 0 9 9 9 9 9 9 9 9 9 9 a a a a a a a a a a a a a a a a a a a a a a 9 9 a 9 9 9 a a a a a a a a a a a a a a } 9 } 9 } a } } } } } } } } } } } } } } b | b b c c c c c 3 d e d d d f d e d e e d e g g g h h g g g h i g g e j } k 7     . . ",
"{ 6 l $ m a 0 n o p q o r r n r r r r r b n b b s b b b b b b b 0 b 0 b 0 b b b b b b b b b b b b b b b b b b b b b b b b c t b r t c r c c c t c r c c t c t t f t t c c c d d d d u u u v w g x x v x g g v x g g y y y y i i i g z z z z z i g e c A 7       ",
"+ ^ $ ) a s B B B C B B B B q q q B p q q o o o r o o o o r n r r r r r r b r n r r o o q o o o D E D r r r r r t t j D j t t t j j r t t c t c t t c j d d u f j d f t t d d u u u u F E j E F D D r t j j D u j E x x x i i G i i z z H H H z z z g d A I     ",
"6 $ J K s B L L L L L B B B B B B B B B B B q q o o o q q q q o o o o o o o o o r o q D M N M M F D o o o o q D D t D F E D E j j j t j c c c b c b c b c c t f j j d N d D u x u d D j D j t t r b r b b r c t r t j F x w O G G P z H Q H R H S z y g 3 T {   ",
"^ $ U 0 p V L L W L L C B B B B B B B B B B B q q q q q q q q q o q o o o o o o o q q N D M O C o q q q M C M M j D F F F E D t j j j D c t t c c c b c b b c c r r r t E E E E u d j j j j D D j r r r r r j b b r r r E D D E O x P P S z z z X S z i v Y l { ",
"# $ K 0 B L L W W L L L L B B B B B B B B B B B B B q q q q q q q o o o q o o o q N D M C F F M q M M F O C F M N F F O F M j j N u j j c t j j t t c c b b c r r r b b r t j D j j r t j D E E j t r b t r r t b b r t t j j E x Z P z z P X P X z z P v 2 U   ",
"# J K n B W ` ` ` W W W L L L C B B C B B B B B B B q q q B q q q q q q q q q q q N M M O C C M M O O O M N o o N N F F F E F N E u u j j j N j j t t b r b c r r r r r t j j t t t t t D E E E E j E j j D D t D t j D x Z D j F F w z P X X P P S S S y  .T   ",
"# J 9 n B ..` ` ` ` +.+.+.L L L C L L C B L B L L C B B B B M B B q q q q D D q D M M O O O C O @.@.O @.M o N N N N N N D E w u F F x u F u F j D D t r r r o j j r r o r o E j D D D j O Z G P P P X P P P G G G G G G G i G O D F Z G X P S Q #.$.#.R z e %.  ",
"# & K n B W W ` ` +.+.W W +.W W L C C B B B C L L C C C C B B M B B D E M D M D M M O O L O O O O &.@.O M D E E N M M E F N F x x x x x x x x F F F j j j o j j j j t r t t t j D E E x Z w G X S S S S S S z P P i P P G P G P w G G S *.$.=.=.-.-.=.#.z ;.%.  ",
"# & 9 n L ..` ` ` ` ` W W W L W C C C B B B C L C C C B C M M M C C M C M M C M E M O M O M M O Z @.Z O E E O O O O O O F F w G Z G G G w G w F w w x F D t j t j j j j j j F u F w G x G G G X P P z z S S S S S S H S *.S *.$.$.#.$.$.=.-.-.-.-.>.-.$.R h %.{ ",
"^ & 9 p W ` ,.` ` ` ` ` ` W +.W L L L B B L L L C M C M M M M C M C M M M M M M C C M M C O @.O Z O O &.Z O O O @.@.O O @.G G Z G P X '.i w w w w G i G w E N x F D F E D x w w G w O x F F P i G G G w w G P S Q #.$.$.#.$.$.-.=.$.$.-.=.-.=.>.-.-.-.=.H h %.  ",
"^ 7 9 p ` ).!.,.,.,.,.!.` ` ,.+.+.+.+.+.L +.+.L L L L C L L C L C C C M C L C M M C M C C C O O @.@.@.@.@.@.@.@.&.P &.@.x O w @.'.S X Q X w F E E E E j j j t o D o j j o D O O @.E j E E x x w w G w x O x w G P S Q #.$.#.$.$.=.=.-.-.>.=.-.-.-.-.>.=.H ;.%.  ",
"^ 7 9 V ` ~.~.!.!.!.!.,.!.,.` ` ` ` +.+.+.+.+.W W W L L L L L L L L M M M C M C M M M C M C C O @.@.&.&.&.'.'.@.{.{.'.G O F &.G {.G G w w w F E E D E j j j t o D D N N o D D D E E j j F F E O G '.&.G '.w G x w '.P Q ].$.$.-.=.-.>.-.-.-.-.-.-.>.>.#.S v %.  ",
"^ & 9 V ` ~.~.!.!.!.!.!.!.,.` +.+.+.+.+.+.+.L +.+.W L L L L L W L L C C C C C C M M M C C L O @.@.@.'.&.&.&.'.'.{.^.P X X &.@.'.'.w P G '.G w E E E D j j t o r o D N j E j o o o o o r j D D O @.F Z x P S *.S S P '.G P P *.#.$.-.-.>.>.-.-.>.-.-.=.$.z e /.. ",
"^ & 0 p ` !.~.~.!.,.,.,.,.,.,.` +.+.+.+.+.+.+.W L L W L W L W +.W L L L L L L L L L L L L L L W @.&.(.{.'.{.&.&.&.&.@.O @.@.@.@.'.'.{.w O O w M O w F F E j j j j N E j t j o D E E j j N D O w @.O @.@.O O P X S H S X {.P i X *.$.-.-.-.>.>.-.-.-.=.R z e %.  ",
"^ & 0 V ` ~.~.~.!.!.!.!.,.,.,.+.` ` ` ` +.+.+.W W W L L L L L W W W L L L L L W L L L L L W @.+.&.&.&.'.&.^.w Z @.&.'.@.'.&.@.O '.X {.{.G '.@.E o O F O O E j j D D E E j o j j D E D N D N F O @.@.O @.&.O @.w x w G X S S X X P $.-.-.>.>.>.>.-.-.].R P e T { ",
"^ & 0 V ,.~.~.~.!.!.!.!.,.,.,.,.,.,.` ,.` +.+.W +.W +.W L L L W W W +.L L L W L W L L L W +.&.&.{.'.'.'.^._.X @.@.(.&.&.'.&.^.(.O X {.X {.@.Z O O F @.w &.O O x F E x F D D D D M E F M D D F O @.O @.O @.G P P w w G P X S *.S :.*.*.-.-.-.>.>.<.<.-.*.i e [.{ ",
"^ 7 0 V ).~.}.~.~.~.~.!.!.!.!.!.!.!.!.,.` ` ` ` ` ` ` ` W W W W W +.(.L W W W W @.W (.(.W W (.(.(.(.^.{.:._.X Z ^.{.(.{.^.^.(.&.'.P |.].P P &.&.G {.{.'.P {.&.@.O O x F F D D D E F Z M M F D O Z O F Z @.O Z G {.X '.X P G X #.S <.].<.<.*.1.|.-.-.<.*.i j T { ",
"^ 7 0 V ).~.}.}.}.~.~.~.2.~.2.2.,.,.,.,.,.` 3.(.` ` ,.` ` W W W 3.W W (.3.3.(.(.(.(.(.(.(.(.(.3.3.^.3._._.1.1.P (.^.(.1._._.{.(.(.'.].<.:.{.{.{.@.&.X P :.:.:.P {.Z Z Z &.G Z O F O O Z Z O E E O Z O Z O O O G G P z G w P *.*.$.-.-.-.<.*.1.*.<.<.].S P d T ] ",
"^ 7 0 V ,.}.}.}.~.~.2.~.~.~.~.~.,.,.,.,.,.` ,.3.3.,.,.,.,.(.(.(.3.3.3.3.3.3.3.3.(.(.W (.,.(.(.(.'.^._.^.1.1.1.1.|._._.|.].|.^.:.{.,.:.|.].:.:.{.{.&.'.X |.].*.X X X ^.:.{._.X '.'.&.&.'.@.O O O Z 3.G ^.P G G ^.{.:.:.S :.*.<.#.<.$.*.*._.S *.*.<.<.*.X G j '   ",
"^ 7 0 V ,.~.}.~.~.~.~.!.~.!.~.~.!.!.,.,.,.,.(.,.,.3.3.,.3.3.(.(.3.3.3.(.(.,.N 1 4.4.F '.,.^.^.,.^.^.^._._._.:.:.|.:.].<.].<.|.^.&.'.^._.|.<.].].:.^.:.^.|.*.].1.:.*.].*._._.:.^.:.^.'.'.{.&.L @.&.(.X ^.3.'.{.{.P ^.{.X :.].-.<.#.5.:.{.:.:.|.6.].6.|.:.Z c T . ",
"^ 7 0 V !.}.}.}.~.~.~.~.~.~.!.^.7.8.9.9.0.a.8.a.a.0.9.9.3.3.3.3.3.2.3.4.b.a.c.c.c.c.d.d.b.u ^._.^._._.^.e.f.g.h.i.j.j.k.l.m.n.S :.^.^._.o.p.l.q.g.i.r.e :.:.:.:.:.s.t.u.u.v.c.s.1.n.j.w.h.x.&.&.^.^.^._.^.'._._.X ^.v g.g.k.p.;.<.<.|.|.].6.*.<.].6.].1.Z t ' ~ ",
"^ 7 0 V !.}.}.}.}.~.~.~.~.}.~.!.~.~.8.y.7.~.2.2.~.2.r z.` ` ,.,.2.E a.d.1 !.2.^._.^.^.1 v.9.A.'.^._.1._.B.|.x.v.e.|.|.5.C.m.q.k.g |.].].*.<.o.u.u.X |.|.|.].|.*.<.|.].s.g.D.:.|.].<.*.E.h.w.w ^.{.{.{._.^.^.^.^.:.1.E.g.u.H -.-.-.1.|.|.|.].<.].].].].1.Z c ' ~ ",
"^ 7 0 F.2.G.H.H.}.}.!.~.}.~.~.~.~.~.a.y.7.!.2.2.~.2.!.b.` ,.,.,.t y.8.@.,.^.^.^.^.^.^._.w x.d.f.^.|.B.I.6.B.A.g.e.6.].].<.].k.J.m.5.K.<.:.].v q.i.1.|.1.].|.:.*.<.<.|.y g.|.1.].<.-.].e.h.g.e.^._.'.^.1.^._.1.^.:.v g.g.g.-.K.-.].1.:.:.|.].|.].].*.|.:.G j ' . ",
"^ 7 0 F.L.M.M.M.H.}.}.}.}.}.}.~.~.L.a.z.7.2.~.~.~.~.!.!.,.!.!.(.y.z.f ^.!.^._.~.^.^.^._.^.@.v.x.E.N.|.6.N.O.P.v.e.6.6.6.<.6.p.i.i.<.5.5.<.].;.q.q.<.|.1.|.|.:.:.<.<.<.6.u.|.|.|.<.*.5.p.t.J.g.y ^.^.:._._.|._.^._.Q.r.h.u.<.-.].].*.|.|.1.|.].].].<.|.:.G d T . ",
"# 7 s F.L.M.R.R.G.H.G.}.G.H.H.}.}.~.b.y.7.~.~.~.~.~.~.~.2.2.~.c.z.a.^.^.^._._.^._.^._.^.^._.E.d.x.g 6.I.N.N.E.g.n.6.6.5.<.6.p.g.P.<.<.<.<.<.;.J.i.<.*.1.:.1.:.1.6.<.<.5.J.<.1.|.:.*.].n.S.n.J.j._._._.:.|.1.:.:.4.g.*.u.g.<.1.<.].].<.<.6.].<.<.<.<.].1.G t ' . ",
"# 7 s ..L.M.M.M.G.G.G.G.H.H.H.}.~.~.b.y.7.~.~.~.~.~.c.c ~.~.2.0.d.7._._.^._.B._._._._._.^._.f v.v.e.N.I.N.N.A.i.p.O.T.6.O.6.Q.q.g 6.5.5.5.K.;.Q.J.5.<.].|.|.1._.|.1.5.<.J.-.<.1.:.:.:.m.;.#.l.J.n.].1.|.<.].<.H v.D.<.v.J._.1.|.].<.<.5.<.6.<.<.<.<.<.1.w t ' . ",
"^ 7 s ..L.M.U.M.G.G.G.G.H.H.H.}.}.}.b.y.c.f c c c 4.0.f ~.~.u d.d.r.}._._.B.B._._._._.B.B.B.P d.d.A.I.N.6.6.A.i.n.O.6.6.i A.E.P 6.<.6.5.5.5.v q.q.5.5.5.5.]._.]._.1.|.5.J.5.<.].<.|.|.j.n.<.s.q.J.#.5.<.<.K.5.p.p.K.5.J.i.:._._.<.5.T.5.5.<.].<.<.<.<.|.{.d T . ",
"^ 7 s ..}.U.U.M.G.G.H.U.G.G.G.V.}.}.b.d.b.7.7.7.7.c.z.c ~.}.f d.d.r.B.B.V.B.V.B.B._.B.B.B._.B.x.g.A.I.N.N.N.A.q.P.A.E.q.i.E.|.6.6.5.5.O.5.6.v q.Q.T.5.5.5.<.5.6._.1.1.<.q.5.<.].5.<.5.m.v 5.-.m.l.W.X.-.K.X.h l.].Y.>.J.J.<.].1.|.5.5.<.<.<.].<.].5.<.:.G D T . ",
"# 7 0 ..}.U.Z.M.Z.H.V.V.U.G.G.G.}.}.b.y.7.~.~.~.}.}.a.c B.}.^.d.d.b.N.V.V.N.N.B.B.B.B.I.B.I.I.v.g.r.N.6.N.6.A.g.p.6.].s.i.i.n.<.<.<.<.5.5.T.;.Q.k.5.5.<.5.<.O.<.5.<.|.6.J.O.5.5.K.5.5.m.;.X.K.C.`.l.;.K.K.K.m. .X.K.Y.J.J.5.5.<.<.<.5.5.<.<.<.<.5.5.].*.P x [.. ",
"# 7 s ..L.R.R.M.Z.V.U.V.G.G.H.H.}.H.b.0.7.}.}.}.H.H.@.{.~.B._.b.d.d.^.I.B.N.N.V.V.N.V.B.B.N.v v.x.v 1.N.6.6.A.i.n.6.6.6.n.i.q.y O.5.T.5.5.O.;.q.q.X 6.6.O.6.6.5.5.5.5.X k.T.5.5.5.5.5.j.h Y. +X.p.l..+<.++S.W.Y.Y.Y.K.l.q.5.5.T.5.5.5.5.<.5.K.T.T.T.<.].X g k . ",
"# 7 s F.~.R.R.Z.Z.Z.@+V.U.H.H.H.}.H.b.0.7.H.H.}.H.V.B.H.}.B.N.d d.d.#+I.V.B.B.V.V.V.B.B.B.I.r.d.P.V.I.6.6.O.E.i.n.N.6.6.6.E.q.Q.|.O.O.6.6.O.<.J.q.o.5.5.O.5.5.5.T.T.5.D.t.T.5.5.5.K.K.`.C. +X.K.<..+`.n.H .+-.Y.Y.Y.Y.l.l.y 5.K.K.K.5.T.5.T.K.T.T.T.T.5.*.w [.. ",
"^ 7 0 ..~.U.U.U.Z.Z.Z.V.M.M.H.H.H.H.b.8.#+V.U.H.H.V.V.V.V.V.V.N.7.d.d.u B.B.B.B.B.B.B.B.I.F d.P._.N.N.N.6.$+m.f.e.N.6.6.6.1.A.q.A.1.O.6.6.<.O.t.i.m.6.O.5.T.5.O.5.5.T.k.o.5.5.5.K.Y.Y.`.C.Y.Y.Y.Y. .%+%+&+ . +Y.Y.Y.Y.l.l.h T.K.K.K.K.K.K.K.T.T.Y.Y.K.5.].i /.. ",
"^ 7 s ..}.Z.*+$+=+Z.Z.Z.Z.R.G.G.}.H.b.8.#+H.V.U.V.@+@+G.V.V.V.V.@+4.8.x.4.B.B.B.B.B.I.V.d x.P._.V.N.I.N.6.O.A.g.#+6.6.6.6.6.X j.i.A.P 6.6.6.5.X Q.q.e.T.5.5.5.5.5.*.e.m.T.T.K.K.Y.Y.C.%+C. +Y.-+-+ +&+%+&+ + + +Y.Y.Y.k.l.C.K.Y.Y. +Y.T.T.K.Y. +Y.Y.Y.5.].y A ~ ",
"^ 7 s ..H.*+;+*+=+$+Z.Z.$+Z.R.^.N #+d.0.8.4.f ~.G.@+@+@+V.V.V.V.V.N.'.#+x.a.#+f f f 4.b.A.c B.B.I.I.N.:.d #+v.v.x.s.w 6.6.6.6.1.A.i.Q.s.6.5.5.5.y t.l.j.p.o.v s.p.m.n.<.K.K.X.Y.$.;.&+.+S.>+=.,+'+-+C.%+h Y.Y. +-.C.S.`.`.W.h $. +Y.K.Y.Y.Y. +Y. +Y.K.5.].P %.. ",
"@ 7 s ..H.*+*+*+*+*+=+=+$+Z.U.Z.N f N N f f f B.B.@+G.@+@+V.V.V.Z.Z.)+V.B.u 4.#+r.#+f ^.V.B.B.B.@+I.I.I.d f d d d e w N.N.6.6.6.6.g n.n.n.*.T.O.T.5.*.v o.n.n.v y T.T.T.K.Y.Y.Y.#.C.>+>+>+>+>.,+'+ + +;.Y. +-+ +-+C.C.C.C.h C.=.!+ + +Y.Y.Y.Y.Y.Y.Y.K.5.:.i ~+. ",
"@ & n ..M.*+;+*+;+;+;+*+*+*+*+Z.L.L.L.).).).).V.}.V.V.@+V.B.}.}.@+@+@+H.B.!...V F.F.!.H.B.B.V.@+I.N.I.N.~.2.2.2.~.~.}.N.N.6.6.6.6.@+~.L.).O.T.5.O.O.N.B.~.2.).V.N.T.T.K.K.Y. +-+Y.++{+++T.++]+'+ + +Y.N.-+-+-+'+'+T.T.O.O.O.O.T. + + +Y.Y. + +Y.Y.K.Y.K.<.i /.. ",
"6 7 n ^+M.;+;+;+/+;+;+;+;+;+*+R.L.(+_+_+_+^+).}.}.@+@+@+@+B.V.V.@+G.~.V _+:+F.2.2.2.` :+:+,.N.N.I.N.N.B.2.F.<+<+_+,.~.N.)+6.6.)+V :+V ~.5.T.5.6.}.V V F.).~.N.}.2.F.~.K. + + +'+]+++L.(+M.++ +'+!+ +T.F.++'+'+'+-+[+U.F.V ).O.T.-+ + + + + + +Y. +T.Y.5.].i ~+~ ",
"6 7 n ^+M.*+*+*+;+*+*+*+*+*+$+$+$+*+V _+..Z.V.@+V.@+@+)+)+Z.V.V.B..._+_+..V.B.B.N.B.B.V.2._+:+V.N.I.I.V.B.B.V <+..I.)+N.6.6.@+V :+F.)+T.5.6.6.N.V V L. +T.T.T.K.Y.++H.).-+'+'+,+}+}+{+(+{+,+'+'+-+,+).(+L.'+'+'+-+-+|+F.F.O. + +!+ +!+ + + + +-+ + +T.Y.].y A ~ ",
"6 7 n ..M.*+*+*+*+*+*+$+$+;+;+*+$+*+V _+F.V.V.V.U.U.U.U.U.V.V.V.V <+<+!.V.V.V.V.I.N.N.V.B.2.<+:+}.B.V.V.I.N.V _+..6.6.6.1+$+V :+V O.5.O.O.O.T.^+V ). + +T.T.++Y. + +|+^+1+,+,+}+,+}+}+(+{+,+,+2+}+1+(+(+L.1+,+'+-+'+-+F.F.3+ +-+]+!+ +!+!+!+!+!+!+-+'+ +].z ~+~ ",
"6 & n ^+M.*+;+*+*+$+*+*+*+;+;+*+$+*+V _+F.V.Z.Z.Z.Z.U.Z.U.V.V.!.<+<+F.V.B.V.@+V.I.N.N.V.B.B.V <+:+B.V.I.N.N.V _+` $+O.O.6.F.:+:+6.T.O.O.5.T.{+V F.)+|+{+T.++Y. +!+'+,+1+H.,+,+}+,+,+,+(+{+2+,+}+'+).(+=+|+^+-+'+-+-+-+F.F.O.]+!+!+]+!+!+]+!+-+++ +{+,+-+>.H 4+. ",
"6 7 p ).R.;+;+*+*+*+;+/+$+*+*+;+$+$+V _+F.Z.Z.Z.U.U.}.G.U.)+$+:+<+<+}.V.@+V.@+I.I.@+@+I.B.B.2.<+<+2.N.)+6.$+V _+^+O.O.O.^+:+:+$+++T.T.T.T.++O.F.F.++ +T.++ +]+'+,+,+'+{+^+'+,+}+,+,+,+5+++,+}+2+M.(+5+]+,+$+}.'+-+-+-+F.F.]+]+]+]+]+]+'+'+]+]+'+'+]+}+'+>.S 6+. ",
"6 7 p ).R.;+;+*+*+;+/+/+;+1+*+*+$+R.V _+(+)+=+$+)+U.:+L.)+)+G._+<+:+B.V.V.V.V.@+@+@+@+@+I.B.B.<+<+F.6.)+6.1+V :+^+O.O.~.:+V H.++++++++++Y.{+/+F.F.-+Y.Y.'+,+,+2+,+,+'+]+F.,+,+}+,+}+,+L.{+}+,+{+^+(+{+,+,+'+).[+'+'+'+F.F.'+'+'+'+7+,+,+,+,+,+8+,+9+9+,+0+R 4+. ",
"6 7 :+).R.;+;+*+;+;+;+;+;+;+*+*+;+$+V _+V (+F.(+(+F.<+L.1+$+).<+<+F.V.V.V.V.V.B.B.V.V.V.V.V.N._+_+V 1+1+O.O.F.:+V F.F.:+V ^+++++{+{+{+{+{+{+/+F.(+|+'+-+]+'+,+,+'+,+,+'+(+}+}+}+,+,+,+H.a+}+}+H.(+M.,+,+,+'+++(+]+2+,+(+F.7+7+7+'+7+2+7+,+2+}+}+}+9+9+,+0+#.b+. ",
"6 7 p ^+R.;+;+;+/+/+/+/+;+;+*+;+;+/+V :+F.L.L.~.L.(+:+H.$+Z.L.<+<+F.V.V.V.V.V.V.V.V.V.V.V.Z.U._+_+F.1+1+O.1+F.:+).[+T.{+/+(+^+c+{+{+{+]+|+]+[+(+(+,+,+-+]+]+,+,+7+'+,+,+(+}+}+}+,+,+8+H./+}+d+(+).]+,+,+'+]+'+U.R.,+8+(+F.7+7+7+7+,+2+}+}+}+}+}+9+9+9+,+0+$.b+. ",
"6 7 p ^+R.;+;+;+d+/+c+;+;+/+/+;+;+;+F._+(+=+Z.=+Z.=+F.}.Z.Z.V._+_+F.N.N.Z.N.N.N.V.Z.)+$+$+)+}.:+:+^+1+1+O.O.F.V L.++++{+{+{+F.F.1+{+]+8+}+,+{+(+^+8+,+,+'+,+,+,+e+,+2+}+5+}+2+,+,+2+,+L.f+e+^+(+/+,+'+,+,+'+'+]+(+++7+(+(+7+7+7+2+}+}+9+9+9+9+g+g+g+9+,+0+=.b+. ",
"6 h+p ).R./+;+c+d+c+c+c+/+;+;+3+3+3+(+:+^+*+=+=+=+$+$+$+)+)+Z.F._+V Z.Z.Z.Z.V.Z.)+$+O.$+1+1+^+:+V }.O.O.O.T.(+F.H.++++{+{+{+U.F.^+e+}+}+}+}+f+5+5+7+,+,+,+8+'+e+e+'+,+2+5+}+}+,+}+}+8+O./+/+5+H.2+7+7+2+2+2+2+2+d+L.,+5+5+2+}+}+2+}+9+9+g+g+g+9+g+9+g+2+0+=.b+. ",
"6 h+p ).R.;+/+a+d+d+++c+/+/+;+;+;+;+(+F.H.;+;+;+3+3+*+$+$+$+$+Z.F.F.L.)+Z.U.V.$+1+1+1+1+[+1+(+F.L.O.O.T.T.++}.^+U.++{+|+{+{+3+H.M.8+}+}+}+}+f+R.H.7+2+2+2+7+7+7+]+]+7+2+R.8+}+}+,+}+}+d+c+M.R.e+7+2+2+2+}+2+,+2+,+3+c+R.R.2+}+}+}+9+9+g+g+g+g+g+g+g+g+2+0+=.b+. ",
"@ h+p L.R.;+i+j+a+a+d+d+/+;+;+/+/+/+H.L.R./+/+/+;+;+$+H.1+*+$+Z.G.^+^+G.)+)+Z.$+1+1+1+1+1+}.L.H.O.[+[+[+[+++Z.G.1+{+{+{+]+]+/+*+c+8+8+8+}+8+7+c+/+2+7+7+7+7+e+'+]+7+7+7+/+2+2+}+8+8+8+f+c+c+f+,+2+2+}+}+}+}+}+}+}+7+c+c+d+}+9+g+9+g+g+k+k+g+k+k+k+k+k+}+0+=.b+. ",
"6 h+V ).*+c+j+j+i+a+a+d+c+/+d+d+d+c+R.H.R./+;+;+/+;+*+G.*+$+$+)+)+@+L.L.U.Z.$+1+/+1+[+1+M.G.1+[+{+++[+{+++++*+*+/+{+]+e+]+a+c+;+|+8+8+8+}+}+e+a+d+]+e+8+e+e+]+]+'+'+'+|+/+[+++{+'+e+,+f+a+d+,+}+8+}+}+9+}+}+9+8+}+8+!+a+f+9+9+9+g+k+k+k+k+k+k+k+k+k+k+9+'+=.b+. ",
"6 h+V L.;+i+j+j+a+a+d+c+c+c+d+d+/+l+l+M.R.M.M.M.l+M.M.M.;+*+*+*+1+)+)+Z.G.G.V.Z.*+*+R.;+[+a+|+a+{+{+{+++1+*+R.R.;+a+/+/+/+/+++|+]+]+8+8+e+f+a+a+/+++{+]+e+]+]+]+]+|+[+=+G.G.$+[+|+f+++a+a+{+8+8+,+2+}+9+9+9+}+}+}+8+}+f+f+e+8+}+g+g+9+g+g+k+k+k+k+k+k+g+0+>.b+. ",
"6 h+V H./+i+j+j+a+d+d+c+/+d+d+d+d+a+d+d+c+d+c+d+d+d+/+;+$+$+3+;+;+1+1+1+/+c+/+/+c+++f+e+e+|+f+[+[+++++[+[+[+{+]+|+{+{+{+|+|+f+]+7+]+]+8+8+8+8+8+]+]+]+]+|+!+!+]+!+{+++{+]+]+e+e+e+8+7+7+8+8+8+8+8+}+}+}+9+}+}+}+}+9+9+g+g+g+g+g+g+9+9+g+g+k+g+g+9+9+g+9+0+=.b+  ",
"6 h+V M.d+i+i+a+a+d+d+c+d+d+d+d+a+a+a+a+a+c+d+d+c+c+/+3+3+;+;+;+;+/+/+/+c+c+d+f+8+8+e+f+e+|+[+[+[+[+[+c+++f+{+f+{+f+{+{+|+|+]+e+]+|+]+e+e+8+}+e+7+]+{+{+!+!+!+!+{+|+7+]+|+]+e+]+e+8+e+e+2+8+8+}+}+}+}+}+}+}+}+}+9+g+9+g+g+9+g+g+k+k+k+k+k+g+k+k+g+k+g+}+0+=.Y   ",
"6 ! B L./+i+i+i+a+d+d+d+d+d+d+d+a+a+a+a+d+d+d+a+d+c+;+;+;+;+;+/+/+c+d+/+c+j+8+8+8+8+e+f+f+[+c+T.++++++|+{+{+f+f+|+{+{+{+{+|+|+]+]+]+]+]+7+8+e+e+]+!+!+{+!+!+!+!+!+7+7+]+!+]+7+7+7+8+8+8+e+7+7+2+}+2+,+}+,+}+9+g+g+g+g+g+g+g+g+g+k+k+k+k+k+k+k+k+k+g+g+}+0+=.} { ",
"+ ! 8 ).;+d+a+j+i+i+i+i+i+d+i+i+j+j+j+d+d+d+a+i+a+c+/+;+/+/+c+/+3+/+c+d+f+8+e+8+e+]+]+|+[+c+T.T.T.++!+!+|+|+{+|+{+{+{+f+|+|+]+|+f+|+7+e+7+]+e+!+!+|+|+|+]+]+7+]+]+7+7+]+!+7+7+]+7+7+7+7+7+!+]+2+2+2+}+2+,+8+}+9+9+9+9+9+g+g+k+k+k+g+k+k+k+k+k+k+k+g+g+2+0+ .m+  ",
"{ @ n+..G./+d+a+j+i+i+i+a+a+a+j+j+i+d+d+d+a+a+j+a+d+;+;+/+/+;+;+3+c+j+e+e+e+e+e+e+e+f+[+O.++[+++{+{+{+!+|+|+]+{+{+{+|+|+f+f+e+]+]+e+]+]+]+7+!+!+!+|+!+!+]+]+]+]+]+7+7+!+7+]+]+7+7+7+7+]+]+]+]+7+8+2+}+}+}+}+2+}+9+9+9+g+g+k+k+k+k+k+k+k+k+k+k+k+k+g+9+7+>.| .   ",
"  + l K ^+U./+d+i+i+d+d+d+d+d+a+i+d+d+d+d+d+a+i+d+;+;+;+;+;+3+3+c+j+f+e+j+e+8+e+f+f+[+c+[+/+[+++{+{+{+++!+!+{+++{+{+{+{+|+]+]+]+|+]+]+]+]+]+!+!+Y.{+{+{+{+|+|+|+]+7+]+7+7+]+]+7+7+]+!+]+7+!+7+2+2+2+2+}+}+,+}+,+}+}+}+}+9+9+9+g+9+9+9+9+}+g+9+g+9+}+,+0+ .m+.   ",
"~   6 h+K L.M.;+/+/+;+*+;+;+;+/+[+/+/+/+;+d+[+/+U.U.G.M.U.)+1+1+/+++a+j+e+e+j+j+j+[+1+1+1+$+1+++++++++++{+T.T.T.c+T.O.[+{+{+++|+|+|+-+ + +-+ +T.T.++T.T.++++++!+-+-+ +]+]+ + +-+ + + +{+{+Y.]+]+]+'+'+,+'+,+'+]+]+'+,+'+,+'+'+}+8+,+,+,+,+e+8+,+}+,+0+;.0       ",
"~ . { @ h+8 ..L.L.L.L.L.}.}.G.G.U.U.U.G.@+*+)+).).^+,.^+~.@+V.@+@+@+O.[+[+[+[+[+O.@+}.~.}.}._.6.6.5.5.5.].N.|.6.I.|.B.I.O.O.6.5.T.K.T.5.5.5.5.<.|.].|.6.O.<.<.<.5.5.5.K.K.K.5.-.5.5.5.<.<.K.K.Y. +Y.Y.Y.K.T.5.K.5.5.K.K.K.K.K.Y. +Y.Y.Y.Y. +-+-+0+>.2 p .       ",
"o+o+. { @ p+h+8 V V V V B V L V L L F.L L ` p p p p p p V p B L L B ^.^.^.^.^.{.3.C B B B B Z {.X _.^.P '.'.&.&.&.'.&.'.^.^.X :.:.S S X X X X X P P {.P X P X X X S S H Q *.S Q X S S y S Q Q #.#.#.*.Q *.S X X S S :.Q S Q #.#.#.#.#.Q #.$.$.$. .} ] . .   .   ",
"o+o+o+. { + ^ p+! h+n+n+n+n+n+h+m ) ) m m & & & & & q+q+& & & 7 m m U r+r+r+r+r+m m ) m U m k s+s+t+t+k k k r+r+r+k s+k k 4 4 s+4 4 t+~+~+~+4 t+~+t+t+t+4 ~+~+6+6+6+6+6+6+6+A A 6+A ~+/.A A 6+4+4+Y 6+6+6+6+6+6+A A 6+6+6+6+4+6+6+4+4+4+Y Y 4+[ u+{     .   .   "};

#endif // BTNFORUMHOVER_H_INCLUDED
